{
 "title": "Sonarqube",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "webjvmstate_systemloadaverage_percent"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "statistics_usercount", "legendFormat": "Users count" },
    { "expr": "statistics_projectcount", "legendFormat": "Projects count" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webjvmstate_maxmemorymb - webjvmstate_freememorymb",
     "legendFormat": "Used"
    },
    { "expr": "webjvmstate_maxmemorymb", "legendFormat": "Max" },
    { "expr": "webjvmstate_freememorymb", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Heap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webjvmstate_heapmaxmb_bytes - webjvmstate_heapusedmb_bytes",
     "legendFormat": "Used"
    },
    { "expr": "webjvmstate_heapmaxmb_bytes", "legendFormat": "Max" },
    { "expr": "webjvmstate_heapusedmb_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Non Heap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webjvmstate_nonheapcommittedmb_bytes - webjvmstate_nonheapusedmb_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "webjvmstate_nonheapcommittedmb_bytes",
     "legendFormat": "Max"
    },
    {
     "expr": "webjvmstate_nonheapusedmb_bytes",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Search Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "searchstate_cpuusage" }
   ]
  },
  {
   "title": "Heap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "searchstate_jvmheapmax_bytes - searchstate_jvmheapused_bytes",
     "legendFormat": "Used"
    },
    { "expr": "searchstate_jvmheapmax_bytes", "legendFormat": "Max" },
    { "expr": "searchstate_jvmheapused_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "searchstate_diskavailable_bytes",
     "legendFormat": "Max"
    },
    { "expr": "searchstate_storesize_bytes", "legendFormat": "Used" },
    {
     "expr": "searchstate_diskavailable_bytes - searchstate_storesize_bytes",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}